# Generated by Django 5.2.6 on 2025-11-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_patient_remove_chatsession_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('cardiac', 'Heart Disease')], max_length=50)),
                ('blood_sugar', models.FloatField(blank=True, null=True)),
                ('blood_pressure_sys', models.FloatField(blank=True, null=True)),
                ('blood_pressure_dia', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='consultation',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
